databases:
  - name: render
    databaseName: render
    user: render

services:
  - type: web
    name: web-authn
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: render
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false